name: Build and Deploy to Self-Hosted

on:
  push:
    branches:
      - master  # Основная ветка для деплоя

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: stop Docker Containers
      run: docker-compose down -v

    - name: Build Docker Containers
      run: docker-compose  build --no-cache

    - name: Start Docker Containers
      run: docker-compose up -d
